# Streamlit Cloud Secrets Configuration
# 
# Add your API keys here in the Streamlit Cloud dashboard:
# 1. Go to your app settings in Streamlit Cloud
# 2. Navigate to "Secrets" tab
# 3. Add the following secrets:

# Example format (don't put real keys in this file):
# GOOGLE_API_KEY = "your-google-api-key-here"
# ANTHROPIC_API_KEY = "your-anthropic-api-key-here"

# Note: This file is a template - real secrets should only be entered
# in the Streamlit Cloud dashboard for security.